site_name: TACTIC System Administration
nav:
    - Planning:
        - 'TACTIC as a Scalable Solution': './deploy-tactic-scalability-solution.md'
        - 'Deployment Preparation': './deploy-tactic-scalability-planning.md'
    - Install TACTIC Application:
        - 'System Requirements': './system-requirements.md'
        - 'General TACTIC Installation': './install-tactic-general.md'
        - 'Install TACTIC on Fedora 30': './install-tactic-rhel.md'
        - 'Install TACTIC on Centos 7': './install-tactic-centos7.md' 
        - 'Install TACTIC Windows Server': './install-tactic-windows-server.md'
        #- 'Install TACTIC with MySQL': './install-tactic-mysql'
        - 'Install TACTIC License': './install-tactic-license.md'
    - Server Configuration:
        - 'Configuration Checklist': './deploy-tactic-checklist.md'
        - 'Assets Storage': './configure-tactic-assets.md'
        - 'Database': './database-configuration.md'
        - 'PostgreSQL': './database-configuration-postgresql.md'
        - 'HTTP IIS 7': './configure-http-iis-7.md'
        - 'SSL': './configure-ssl.md'
        - 'Active Directory': './active-directory.md'
        #- 'LDAP': './ldap.md'
        - 'Email / Mailserver': './setup-email.md'
        - 'Database Resources': './resource.md'
        #- 'Configure Remote Repo': './configure-remote-repo.md'
        - 'Configuration Directives': './configure-tactic.md'
    - Upgrade TACTIC:
        - 'Upgrade Tactic': './upgrade-tactic.md'
        - 'Upgrade to Python 3': './upgrade-python.md'
        - 'PyCryptodome Update': './upgrade-crypto.md'
        - 'Multiple TACTIC Versions': './multiple-tactic-services.md'
    - Scalability:
        - 'Configuration Examples': './deploy-tactic-scalability-configuration-examples.md'
        - 'Load Balancing Tactic': './load-balancing-tactic.md'
    - Troubleshooting:
        - 'Troubleshooting Tactic': './troubleshooting-tactic.md'
    - Maintenance:
        - 'Backup And Restore Server': './backup-and-restore-server.md'
        - 'Automated Backup': './automate-database-backup.md'
        - 'Configure Logrotate': './maintenance-logs.md'
    - TACTIC Server VM:
        - 'Setup And Install': './tsi-setup-and-install.md'
        - 'Troubleshooting': './tsi-troubleshooting.md'
        #- 'Moving Data': './tsi-moving-data.md'

theme: material
