site_name: TACTIC System Administration
nav:
    - Planning:
        - 'TACTIC as a Scalable Solution': './deploy-tactic-scalability-solution.md'
        - 'Deployment Preparation': './deploy-tactic-scalability-planning.md'
    - Install TACTIC Application:
        - 'System Requirements': './system-requirements.md'
        - 'General TACTIC Installation': './install-tactic-general.md'
        - 'Install TACTIC on RHEL': './install-tactic-rhel.md'
        - 'Install TACTIC Windows Server 2016': './install-tactic-windows-server-2016'
        - 'Install TACTIC License': './install-tactic-license.md'
    - Server Configuration:
        - 'Multiple TACTIC Services': './multiple-tactic-services.md'
        - 'Configure Http Apache': './configure-http-apache.md'
        - 'Configure Http Iis 7': './configure-http-iis-7.md'
        - 'Database Configuration': './database-configuration.md'
        - 'Configure TACTIC': './configure-tactic.md'
        - 'Configure TACTIC Service': './configure-tactic-service.md'
        - 'Configure Ssl': './configure-ssl.md'
        - 'Active Directory': './active-directory.md'
        - 'Deploy TACTIC Configuration': './deploy-tactic-configuration.md'
        - 'Setup Email': './setup-email.md'
        - 'Configure Http': './configure-http.md'
        - 'Resource': './resource.md'
        - 'Remote Access Tactic': './remote-access-tactic.md'
    - Upgrade TACTIC:
        - 'Upgrade to Python 3': './upgrade-python.md'
        - 'Upgrade Tactic': './upgrade-tactic.md'
        - 'Pycryptodome Update': './upgrade_crypto.md'
    - Fileserver:
        - 'Relocate Assets Directory': './relocate-assets-directory.md'
        - 'Configure Remote Repo': './configure-remote-repo.md'
    - Scalability:
        - 'Deploy Tactic Scalability Configuration Examples': './deploy-tactic-scalability-configuration-examples.md'
        - 'Load Balancing Tactic': './load-balancing-tactic.md'
    - Troubleshooting:
        - 'Troubleshooting Tactic': './troubleshooting-tactic.md'
        - 'Monitor Server Performance': './monitor-server-performance.md'
        
    - Maintenance:
        - 'Backup And Restore Server': './backup-and-restore-server.md'
        - 'Automate Database Backup': './automate-database-backup.md'
        - 'Maintenance Logs': './maintenance-logs.md'
    - TACTIC Server VM:
        - 'Setup And Install': './tsi-setup-and-install.md'
        - 'Troubleshooting': './tsi-troubleshooting.md'
        - 'Moving Data': './tsi-moving-data.md'
    - Client Setup:
        - 'Setup Client Computer': './setup-client-computer.md'

theme: material
#theme: readthedocs 
#theme: cinder
