site_name: TACTIC Developer Docs
nav:
    - Developer Start-up:
        - 'Development Concepts': './development-concepts.md'
        - 'Architecture Overview': './architecture-overview.md'
        - 'Tactic Script Editor': './tactic-script-editor.md'
        - 'Setting Up Dev Environment': './setting-up-dev-environment.md'
        - 'Watch Folder Service': './watch-folder-service.md'
    - Client API:
        - 'Client Api Setup': './client-api-setup.md'
        - 'Client Api Structure': './client-api-structure.md'
        - 'Client Api Basic': './client-api-basic.md'
        - 'Client Api Checkin': './client-api-checkin.md'
        - 'Client Api Dependency': './client-api-dependency.md'
        - 'Custom Interfaces In Tactic': './custom-interfaces-in-tactic.md'
        - 'Client Api Performance': './client-api-performance.md'
        - 'Client Api Hierarchy': './client-api-hierarchy.md'
    - Changes:
        - 'Search Id To Search Code': './search-id-to-search-code.md'
    - Custom Widgets:
        - 'Custom Layout Editor': './custom-layout-editor.md'
        - 'Widget Development': './widget-development.md'
        - 'Tactic Widgets': './tactic-widgets.md'
    - Plugins:
        - 'Plugin Manager Interface': './plugin-manager-interface.md'
        - 'Create A Plugin': './create-a-plugin.md'
        - 'Packaging A Plugin': './packaging-a-plugin.md'
        - 'Plugin Versions': './plugin-versions.md'
        - 'Packaging Python Scripts Into A Plugin': './packaging-python-scripts-into-a-plugin.md'
    - Expression Development:
        - 'Using Expressions In Scripting': './using-expressions-in-scripting.md'
    - Validation:
        - 'Setup Validation': './setup-validation.md'
    - Async Loading:
        - 'Loading': './loading.md'
    - Messaging:
        - 'Messaging': './messaging.md'
    - Triggers:
        - 'Python Trigger In Tactic Editor Guideline': './python-trigger-in-tactic-editor-guideline.md'
        - 'Trigger': './trigger.md'
        - 'Setting Up The Schedule Event Trigger': './setting-up-the-schedule-event-trigger.md'
    - Checkins:
        - 'Tactic Checkin Process': './tactic-checkin-process.md'
        - 'Custom Checkin Pipeline': './custom-checkin-pipeline.md'
    - Conventions:
        - 'Naming Convention Classes': './naming-convention-classes.md'
    - TACTIC Python Client API Reference:
        - 'Python Client Api General   Init  ': './python-client-api_general___init__.md'
        - 'Python Client Api General Get Protocol': './python-client-api_general_get_protocol.md'
        - 'Python Client Api General Set Login Ticket': './python-client-api_general_set_login_ticket.md'
        - 'Python Client Api General Set Project': './python-client-api_general_set_project.md'
        - 'Python Client Api General Set Protocol': './python-client-api_general_set_protocol.md'
        - 'Python Client Api General Set Server': './python-client-api_general_set_server.md'
        - 'Python Client Api General Set Site': './python-client-api_general_set_site.md'
        - 'Python Client Api General Abort': './python-client-api_general_abort.md'
        - 'Python Client Api General Add Config Element': './python-client-api_general_add_config_element.md'
        - 'Python Client Api General Add Dependency': './python-client-api_general_add_dependency.md'
        - 'Python Client Api General Add Dependency By Code': './python-client-api_general_add_dependency_by_code.md'
        - 'Python Client Api General Add Directory': './python-client-api_general_add_directory.md'
        - 'Python Client Api General Add File': './python-client-api_general_add_file.md'
        - 'Python Client Api General Add Group': './python-client-api_general_add_group.md'
        - 'Python Client Api General Add Initial Tasks': './python-client-api_general_add_initial_tasks.md'
        - 'Python Client Api General Build Search Key': './python-client-api_general_build_search_key.md'
        - 'Python Client Api General Build Search Type': './python-client-api_general_build_search_type.md'
        - 'Python Client Api General Check Access': './python-client-api_general_check_access.md'
        - 'Python Client Api General Checkout': './python-client-api_general_checkout.md'
        - 'Python Client Api General Clear Upload Dir': './python-client-api_general_clear_upload_dir.md'
        - 'Python Client Api General Connect Sobjects': './python-client-api_general_connect_sobjects.md'
        - 'Python Client Api General Create Note': './python-client-api_general_create_note.md'
        - 'Python Client Api General Create Search Type': './python-client-api_general_create_search_type.md'
        - 'Python Client Api General Create Snapshot': './python-client-api_general_create_snapshot.md'
        - 'Python Client Api General Create Task': './python-client-api_general_create_task.md'
        - 'Python Client Api General Delete Sobject': './python-client-api_general_delete_sobject.md'
        - 'Python Client Api General Directory Checkin': './python-client-api_general_directory_checkin.md'
        - 'Python Client Api General Download': './python-client-api_general_download.md'
        - 'Python Client Api General Eval': './python-client-api_general_eval.md'
        - 'Python Client Api General Execute Cmd': './python-client-api_general_execute_cmd.md'
        - 'Python Client Api General Execute Js Script': './python-client-api_general_execute_js_script.md'
        - 'Python Client Api General Execute Pipeline': './python-client-api_general_execute_pipeline.md'
        - 'Python Client Api General Execute Python Script': './python-client-api_general_execute_python_script.md'
        - 'Python Client Api General Finish': './python-client-api_general_finish.md'
        - 'Python Client Api General Generate Ticket': './python-client-api_general_generate_ticket.md'
        - 'Python Client Api General Get All Children': './python-client-api_general_get_all_children.md'
        - 'Python Client Api General Get All Dependencies': './python-client-api_general_get_all_dependencies.md'
        - 'Python Client Api General Get All Paths From Snapshot': './python-client-api_general_get_all_paths_from_snapshot.md'
        - 'Python Client Api General Get Base Dirs': './python-client-api_general_get_base_dirs.md'
        - 'Python Client Api General Get By Code': './python-client-api_general_get_by_code.md'
        - 'Python Client Api General Get By Search Key': './python-client-api_general_get_by_search_key.md'
        - 'Python Client Api General Get Child Types': './python-client-api_general_get_child_types.md'
        - 'Python Client Api General Get Client Api Version': './python-client-api_general_get_client_api_version.md'
        - 'Python Client Api General Get Client Dir': './python-client-api_general_get_client_dir.md'
        - 'Python Client Api General Get Client Version': './python-client-api_general_get_client_version.md'
        - 'Python Client Api General Get Column Info': './python-client-api_general_get_column_info.md'
        - 'Python Client Api General Get Column Names': './python-client-api_general_get_column_names.md'
        - 'Python Client Api General Get Config Definition': './python-client-api_general_get_config_definition.md'
        - 'Python Client Api General Get Connected Sobject': './python-client-api_general_get_connected_sobject.md'
        - 'Python Client Api General Get Connected Sobjects': './python-client-api_general_get_connected_sobjects.md'
        - 'Python Client Api General Get Dependencies': './python-client-api_general_get_dependencies.md'
        - 'Python Client Api General Get Expanded Paths From Snapshot': './python-client-api_general_get_expanded_paths_from_snapshot.md'
        - 'Python Client Api General Get Full Snapshot Xml': './python-client-api_general_get_full_snapshot_xml.md'
        - 'Python Client Api General Get Handoff Dir': './python-client-api_general_get_handoff_dir.md'
        - 'Python Client Api General Get Home Dir': './python-client-api_general_get_home_dir.md'
        - 'Python Client Api General Get Info From User': './python-client-api_general_get_info_from_user.md'
        - 'Python Client Api General Get Input Tasks': './python-client-api_general_get_input_tasks.md'
        - 'Python Client Api General Get Interaction Count': './python-client-api_general_get_interaction_count.md'
        - 'Python Client Api General Get Md5 Info': './python-client-api_general_get_md5_info.md'
        - 'Python Client Api General Get Message': './python-client-api_general_get_message.md'
        - 'Python Client Api General Get Output Tasks': './python-client-api_general_get_output_tasks.md'
        - 'Python Client Api General Get Parent': './python-client-api_general_get_parent.md'
        - 'Python Client Api General Get Parent Type': './python-client-api_general_get_parent_type.md'
        - 'Python Client Api General Get Path From Snapshot': './python-client-api_general_get_path_from_snapshot.md'
        - 'Python Client Api General Get Paths': './python-client-api_general_get_paths.md'
        - 'Python Client Api General Get Pipeline Processes': './python-client-api_general_get_pipeline_processes.md'
        - 'Python Client Api General Get Pipeline Processes Info': './python-client-api_general_get_pipeline_processes_info.md'
        - 'Python Client Api General Get Pipeline Xml': './python-client-api_general_get_pipeline_xml.md'
        - 'Python Client Api General Get Pipeline Xml Info': './python-client-api_general_get_pipeline_xml_info.md'
        - 'Python Client Api General Get Plugin Dir': './python-client-api_general_get_plugin_dir.md'
        - 'Python Client Api General Get Preallocated Path': './python-client-api_general_get_preallocated_path.md'
        - 'Python Client Api General Get Preference': './python-client-api_general_get_preference.md'
        - 'Python Client Api General Get Related Types': './python-client-api_general_get_related_types.md'
        - 'Python Client Api General Get Resource Path': './python-client-api_general_get_resource_path.md'
        - 'Python Client Api General Get Server Api Version': './python-client-api_general_get_server_api_version.md'
        - 'Python Client Api General Get Server Version': './python-client-api_general_get_server_version.md'
        - 'Python Client Api General Get Snapshot': './python-client-api_general_get_snapshot.md'
        - 'Python Client Api General Get Table Info': './python-client-api_general_get_table_info.md'
        - 'Python Client Api General Get Ticket': './python-client-api_general_get_ticket.md'
        - 'Python Client Api General Get Types From Instance': './python-client-api_general_get_types_from_instance.md'
        - 'Python Client Api General Get Unique Sobject': './python-client-api_general_get_unique_sobject.md'
        - 'Python Client Api General Get Virtual Snapshot Path': './python-client-api_general_get_virtual_snapshot_path.md'
        - 'Python Client Api General Get Widget': './python-client-api_general_get_widget.md'
        - 'Python Client Api General Group Checkin': './python-client-api_general_group_checkin.md'
        - 'Python Client Api General Insert': './python-client-api_general_insert.md'
        - 'Python Client Api General Insert Multiple': './python-client-api_general_insert_multiple.md'
        - 'Python Client Api General Insert Update': './python-client-api_general_insert_update.md'
        - 'Python Client Api General Log': './python-client-api_general_log.md'
        - 'Python Client Api General Log Message': './python-client-api_general_log_message.md'
        - 'Python Client Api General Query': './python-client-api_general_query.md'
        - 'Python Client Api General Query Snapshots': './python-client-api_general_query_snapshots.md'
        - 'Python Client Api General Reactivate Sobject': './python-client-api_general_reactivate_sobject.md'
        - 'Python Client Api General Redo': './python-client-api_general_redo.md'
        - 'Python Client Api General Retire Sobject': './python-client-api_general_retire_sobject.md'
        - 'Python Client Api General Set Config Definition': './python-client-api_general_set_config_definition.md'
        - 'Python Client Api General Set Current Snapshot': './python-client-api_general_set_current_snapshot.md'
        - 'Python Client Api General Set Preference': './python-client-api_general_set_preference.md'
        - 'Python Client Api General Set Widget Settings': './python-client-api_general_set_widget_settings.md'
        - 'Python Client Api General Set Widget Settings': './python-client-api_general_set_widget_settings.md'
        - 'Python Client Api General Simple Checkin': './python-client-api_general_simple_checkin.md'
        - 'Python Client Api General Split Search Key': './python-client-api_general_split_search_key.md'
        - 'Python Client Api General Start': './python-client-api_general_start.md'
        - 'Python Client Api General Subscribe': './python-client-api_general_subscribe.md'
        - 'Python Client Api General Undo': './python-client-api_general_undo.md'
        - 'Python Client Api General Unsubscribe': './python-client-api_general_unsubscribe.md'
        - 'Python Client Api General Update': './python-client-api_general_update.md'
        - 'Python Client Api General Update Config': './python-client-api_general_update_config.md'
        - 'Python Client Api General Update Multiple': './python-client-api_general_update_multiple.md'
        - 'Python Client Api General Upload File': './python-client-api_general_upload_file.md'
theme: material
