site_name: TACTIC Workflow Documentation
nav:
    - 'Introduction': './index.md'
    - 'Workflow Editor':
        - 
    - 'Triggers and Notifications':
        -
    - 
theme: material
markdown_extensions:
  - codehilite
