site_name: TACTIC Workflow Documentation
nav:
    - 'Introduction': './index.md'
    - Creating Workflows:
        - 'Workflow Editor': './workflow-basic-editor.md'
        - 'Manual and Approval Nodes': './workflow-basic-node-manual-approval.md'
        - 'Action Node': './workflow-basic-node-action.md'
        - 'Conditional Node': './workflow-basic-node-conditional.md'
        - 'Hierarchy Node': './workflow-basic-hierarchy.md'
        - 'Dependency Node': './workflow-basic-dependency.md'
        - 'Progress Node': './workflow-basic-progress.md'
        - 'Schedule Preview': './workflow-basic-schedule-preview.md'
    - Executing Workflows:
        - 'Default Workflow Triggers': './workflow-execute-default-triggers.md'
        - 'Execute a Workflow': './workflow-execute-basic.md' 
        - 'Workflow Widgets': './workflow-execute-widget.md'
    - Developing Workflows:
        - 'Custom Nodes': './workflow-developer-node.md'
        - 'Custom Scripting': './workflow-developer-script.md'
        - 'Custom Classes': './workflow-developer-class.md'
    - Notifications: 
        - 'Creating Notifications': './workflow-notification-create.md'
        - 'Notification Log': './workflow-notification-log.md' 
    - 'Triggers': './workflow-triggers.md'
    - TACTIC Services:
        - 'Enabling services': './workflow-services-enable.md'    
        - 'Watch Folder': './workflow-services-watch-folder.md'
        - 'Job Queue': './workflow-services-job-queue.md'
      #### TODO: Migrate information out of old docs into new docs.
    # Copied from Setup docs
    - UPDATE-Advanced Workflow:
        - 'Project Workflow': './project-workflow.md'
        - 'Pipeline Process Options': './pipeline-process-options.md'
    - UPDATE-Project Workflow Introduction:
        - 'Project Workflow Introduction': './project-workflow-introduction.md'
    - UPDATE-Advanced Automation:
        - 'Tactic Event System': './tactic-event-system.md'
        - 'Project Automation Triggers': './project-automation-triggers.md'
        - 'Project Automation Notifications': './project-automation-notifications.md'
        - 'Advanced Notification Setup': './advanced-notification-setup.md'
        - 'Advanced Event Usage': './advanced-event-usage.md'
        - 'Advanced Trigger Setup': './advanced-trigger-setup.md'
        - 'Configuration Workflow': './configuration-workflow.md'
        - 'Configuration Notifications': './configuration-notifications.md'
        - 'Configuration Triggers': './configuration-triggers.md'
    # Copied From Developer docs      
    - UPDATE-Triggers:
        - 'Python Trigger In Tactic Editor Guideline': './python-trigger-in-tactic-editor-guideline.md'
        - 'Trigger': './trigger.md'
        - 'Setting Up The Schedule Event Trigger': './setting-up-the-schedule-event-trigger.md'
theme: material
markdown_extensions:
  - codehilite
